# Site settings
title: Dotkom
header-img: img/cover.jpg
copyright_name: Dotkom / András Somi
description: "Adventures in data, tech and investing"
baseurl: ""
url: "http://dotkomblog.com"
twitter_username: somiandras
github_username:  somiandras
facebook_username:  Dotkomblog
email_username: dotkomblog@gmail.com
linkedin_username: somiandras

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:
gtm_id: GTM-M3H23V

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, github-pages, jekyll-gist]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Somi András"
      comments: true
      header-img: img/post_head.jpg