# Site settings
title: Dotkom
header-img: img/control_room.jpg
email: your-email@yourdomain.com
copyright_name: Dotkom/Somi András
description: "Technológia pénzügyi szemmel"
baseurl: ""
url: "https://doktorjustice.github.io/"
twitter_username: doktor_justice
github_username:  doktorjustice
facebook_username:  Dotkomblog
email_username: dotkomblog@gmail.com
linkedin_username: somiandras

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:
gtm_id: GTM-M3H23V

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, github-pages]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Somi András"
      comments: true