# Site settings
title: Dotkom
copyright_name: Dotkom / András Somi
description: "Adventures in data, tech and investing"
baseurl: ""
url: "http://dotkomblog.com"
twitter_username: somiandras
github_username:  somiandras
facebook_username:  Dotkomblog
email_username: dotkomblog@gmail.com
linkedin_username: somiandras

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:
gtm_id: GTM-M3H23V

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-feed
  - github-pages 
  - jekyll-gist

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Somi András"
      comments: true
      header-url: https://images.unsplash.com/reserve/uZYSV4nuQeyq64azfVIn_15130980706_64134efc6e_o.jpg?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1900&fit=crop&s=a2f2e5fe166600230076297782dfbf8f
      photo-author-profile: amadorloureiroblanco
      photo-author: Amador Loureiro